# This file is used to deploy the postgres database in the kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.1
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: reviewvideo
          - name: POSTGRES_PASSWORD
            value: reviewvideo
          - name: POSTGRES_DB
            value: reviewvideo
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec: 
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewvideo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviewvideo
  template:
    metadata:
      labels:
        app: reviewvideo
    spec:
      containers:
        - name: reviewvideo
          image: fredmfarias88/devops4dev-review:v1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Database=reviewvideo;Username=reviewvideo;Password=reviewvideo" 
---
apiVersion: v1
kind: Service
metadata:
  name: reviewvideo
spec:
  selector:
    app: reviewvideo
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer